name: Bot de Vuelos Telegram
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 

jobs:
  buscar-y-avisar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        
      - name: Instalar librerías desde requirements.txt
        run: pip install -r requirements.txt

      - name: Ejecutar script de alertas
        run: python3 main.py