name: Mi primera automatizacion
on:
  push:
    branches:
      - main

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Ejecutar script
        run: python3 main.py